### ISSUE TITLE
Permission issue of /var/run/docker.sock volume while docker backend enabled

### ISSUE THREAD

**Issue by leopku** [rawmind0/alpine-traefik#21]
Thanks for this awesome image.

system: ubuntu 14.04 LTS

docker info
```
Containers: 11
 Running: 10
 Paused: 0
 Stopped: 1
Images: 13
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 59
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.13.0-105-generic
Operating System: Ubuntu 14.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.736 GiB
Name: VM-160-161-ubuntu
ID: BZZK:ACYM:OK3Q:7C6T:XHS3:CH2N:22FU:3ZFB:VYIZ:6UJT:7P2O:O5JG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

```
# traefik.toml
[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
```

 `docker run -P -v /var/run/docker.sock:/var/run/docker.sock rawmind/alpine-traefik` 

The user `traefik` had no permission to access /var/run/docker.sock in container 

```
bash-4.3$ ls -l /var/run/docker.sock                                                                                                       
srw-rw----    1 root     ping             0 Jan  4 07:43 /var/run/docker.sock 
```

Traefik with Docker backend mode works failed.

Any idea?

**Comment by rawmind0** [comment]
Hi @leopku ...

i think you could try to do it in three different ways:
- Using unix socket: As you are mapping unix socket from the host, you would need to create traefik user (10001) in your host and add it to the /var/run/docker.sock group, that has read/write permission.
- Using tcp socket: Instead of mapping the unix socket, you could activate and use docker tcp socket and configure it as docker endpoint in your traefik. 
- Using official traefik docker, that run traefik as root user. https://github.com/containous/traefik-library-image ;)

By the moment, this image is intended to autogenerate config file and it's integrated with kubernetes and rancher with cattle scheduler (launched with rancher-alpine https://github.com/rawmind0/alpine-traefik/tree/master/rancher )

Best regards....

**Comment by leopku** [comment]
Got it.
Thanks a lot.

**Comment by publicocean0** [comment]
Sorry a clarification : 

> create traefik user (10001) in your host and add it to the /var/run/docker.sock group, that has read/write permission

 (host machine)ls -l /var/run/docker.sock 
srw-rw----. 1 root docker 0 12 giu 17.23 /var/run/docker.sock
 
it is sufficient i add traefik user to docker group?
