### ISSUE TITLE
Utilize rancher-backend

### ISSUE THREAD

**Issue by adepretis** [rawmind0/alpine-traefik#37]
Since a few versions traefik has a "native" Rancher backend - do you have any plans of using it, instead the current implementation?

**Comment by rawmind0** [comment]
Hi @adepretis ...

With this image, you could use 2 different rancher integration. Traefik built-in rancher integration, TRAEFIK_RANCHER_ENABLE="false" and the unofficial rancher integration with rancher-traefik. In rancher-traefik is not yet implemented the traefik.frontend.auth.basic label, but yes in traefik built-in rancher integration.

Traefik built-in rancher integration has a "bug" that needs an admin api key for work. The bug is addressed to Traefik team and it will be solved in next traefik release. Once it would be solved, i'll change traefik catalog package in rancher, just to use the built-in integration and not rancher-traefik. :)

Best regards...

**Comment by adepretis** [comment]
that's great news, thank you very much @rawmind0

**Comment by rawmind0** [comment]
Hi @adepretis ...

In last alpine-traefik release, 1.4.0-3 traefik built in rancher integration is supported, metadata and api. Also, community-catalog is already updated. Now 3 rancher integration are available, metadata, api ( traefik built in) or external (rancher-traefik). 

Take into account that labels are different with traefik built in integration, https://docs.traefik.io/configuration/backends/rancher/#labels-overriding-default-behaviour
Metadata with longpoll is the prefered integration, it’s working so good. :)

Best regards...

**Comment by rawmind0** [comment]
Closing....Please reopen if you have any problem...
