### ISSUE TITLE
traefik.alias not work anymore in 1.4.0-3

### ISSUE THREAD

**Issue by sirius1024** [rawmind0/alpine-traefik#54]
I've installed traefik on rancher version is v1.4.0-rancher-1
but traefik.alias not work. traefik dashboard didn't show the alias domain and cannot proxy it correctly.
I have to rollback to version **1.3.6**

Rancher server: Ubuntu 16.04
Rancher version: 1.6.7
traefik on rancher: v1.4.0-rancher-1(from rancher catlog)

**Comment by rawmind0** [comment]
Hi @sirius1024 ... 

what kind of rancher integration are you using?? Metadata, api or external??

 Traefik.alias support is provided by rancher-traffic and it’s working. you need to select external rancher integration. 

As you could read in the community package readme, If you are using metadata or api rancher integration the labels used are different due to is using built in support from traefik .
https://docs.traefik.io/configuration/backends/rancher/#labels-overriding-default-behavior

Best regards...

**Comment by rawmind0** [comment]
Closing...Please @sirius1024 reopen it if you need.

**Comment by sirius1024** [comment]
@rawmind0 Sorry for my late. I've tried set integration's value to external of traefik and it worked. Thanks for your help!

**Comment by Theaxiom** [comment]
@sirius1024 I am having the same issue, nothing past version 1.3.6 works. What do you mean by "I've tried set integration's value to external of traefik and it worked."?

**Comment by sirius1024** [comment]
@Theaxiom Hey man, now I'm using traefik 1.6.5 on rancher, the integration option has to select external. ⬇️
![image](https://user-images.githubusercontent.com/6395714/45333381-7bbe4380-b5a8-11e8-8aec-1627025838a9.png)

**Comment by Theaxiom** [comment]
Thanks @sirius1024
