### ISSUE TITLE
Additional HTTP-Methods via Matchers

### ISSUE THREAD

**Issue by Hermsi1337** [rawmind0/alpine-traefik#59]
Hey,

I am wondering if it is possible to allow additional HTTP-Methods like PURGE for Varnish.

In the Traefik-Docs I found out that it is basically possible to add new methods via matchers:
https://docs.traefik.io/basics/#matchers

But I can't figure out how to realize new methods using rancher.

For now, when my traefik receives a "PURGE"-Request, it discards it and forwards to default "GET":
```
XXX.XX.XXX.XX - - [27/Oct/2017:16:06:47 +0000] "PURGE /.* HTTP/1.1" - - "http://varnish.domain.de/.*" "WordPress/4.8.2; http://varnish.domain.de" 3193 "Host-dev-varnish-varnish" - 0ms
XXX.XX.XXX.XX - - [27/Oct/2017:16:06:47 +0000] "GET /.* HTTP/1.1" 403 519 "https://varnish.domain.de/.*" "WordPress/4.8.2; http://varnish.domain.de" 3194 "Host-varnish-varnish-de" "http://XX.XX.XX.XX:8080" 5ms
```

Does one of you guys have a clue?

Thanks!

**Comment by Hermsi1337** [comment]
Okay, main problem is, that I get a "302 Found" and the "302"-redirect does not forward the HTTP-method properly.. any ideas on that?

**Comment by rawmind0** [comment]
PURGE is not an http rfc definition....To force redirect may be you need an reverse proxy to manage it...What happens if you go directly to https instead http and making traefik to redirect??

For configuring matchers, you should use labels in the services. 
In the case of traefik rancher services, https://docs.traefik.io/configuration/backends/rancher/#labels-overriding-default-behaviour

Anyway, this question should be opened at traefik git repo. ;)
