### ISSUE TITLE
add redirect from http to https support 

### ISSUE THREAD

**Issue by naerion89** [rawmind0/alpine-traefik#92]
Can you add the support for the variable [entryPoints.http.redirect] in traefik.toml and rancher catalog ?

**Comment by rawmind0** [comment]
`[entryPoints.http.redirect]` is already managed by `TRAEFIK_HTTPS_ENABLE="false"	# "true" enables https and http endpoints. "Only" enables https endpoints and redirect http to https.`

**Comment by naerion89** [comment]
Ok, it works.
Thanks you

**Comment by claflico** [comment]
@rawmind0 I was just about to post a question about this very thing based upon some testing I did tonight in my Rancher environment. I'm not sure if it's a bug or a misunderstanding on my part.

Say I have 10 urls going through my traefik. 9 of them I want to automatically redirect to https but 1 I want to stay http. 

If I set TRAEFIK_HTTPS_ENABLE=only, then the 9 url automatically redirect to https. But, the 1 url that I want to stay http also redirects to https even though I've experimented setting variations of traefik.protocol=http, traefik.frontend.entryPoints=http, & traefik.frontend.redirect.entryPoint=http on that service.

If I set TRAEFIK_HTTPS_ENABLE=true, then the http url DOES NOT redirect to https. However, in order to get the other 9 urls to redirect to HTTPS I have to add the traefik.frontend.redirect.entryPoint=https label to each of those services.

Ideally I'd prefer to have to only add additional labels to the 1 http service rather than the 9 https services.

If you want this as a separate issue then I can create a new one.

**Comment by emcniece** [comment]
Yeah, I'm starting to think that this needs to be available as an option at service-level as well as load-balancer-level.

My use case is within Rancher. I set `TRAEFIK_HTTPS_ENABLE="true"` on the `rawmind/alpine-traefik` container to enable certificate management, then on my individual services I add `traefik.enable=true` and `traefik.frontend.rule` labels. This works fine for most cases, except:

- I can't set `TRAEFIK_HTTPS_ENABLE="only"` because some service stacks don't support SSL
- The service stacks expect traffic on `:80` and I expect `rawmind/alpine-traefik` to handle SSL termination as well as redirects up to `:443` before load balancing

The real problem I have now is that my services that use Nginx FastCGI caching are caching both HTTP and HTTPS requests that come through Traefik. It may be possible to perform the 301 at the lower Nginx instance, or even at the bottom-most application layer... but I would rather let Traefik handle the routing as advised by Rancher for a more immutable environment.
